name: Service connectivity test
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6.6-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: 'users'
          POSTGRES_USER: 'admin'
          POSTGRES_PASSWORD: 'admin'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: 
      image: node:10.16-jessie
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - name: Test connection
      run: node index.js
