name: Service connectivity test
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6.6-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: 'users'
          POSTGRES_USER: 'admin'
          POSTGRES_PASSWORD: 'admin'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Test connection
      run: node index.js
